name: Intro to ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
      #recupéré les actions de la commu
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          run_install: false

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build


      #- name: Setup PNPM
      #  uses: pnpm/action-setup@v2.4.0
      #  with:
      #    version: 8
      #    run_install: false

      #- name: Install dependencies
      #  run: pnpm install

      #- name: Build
      #  run: pnpm run build