name: Intro to ci

on:
  push:
env:
  NAME: toto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
      #recupéré les actions de la commu
        uses: actions/checkout@v4

      - run: echo "hellp ${{ env.NAME }}"

      #- name: Setup PNPM
      #  uses: oven-sh/setup-bun@v1
      #  with:
      #    bun-version: latest
      #    run_install: false

      #- name: Install dependencies
      #  run: bun install

      #- name: Build
      #  run: bun run build


      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build