name: Intro to ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
      #recupéré les actions de la commu
        uses: actions/checkout@v4
      #-name: Run a onle-line script

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build